name: test-variables

on:
  push:
    branches:
      - "main"

env:
  user_name: "purva"
  demo_name: "variable_demo"

jobs:
  test_variables:
    runs-on: ubuntu-latest
    steps:
      - name: run variables
        run: |
          echo "hello ${{ env.user_name }} !"
          echo "welcome to ${{ env.demo_name }} !"
          echo "hello $user_name !"
          echo "wrlcome to $demo_name"
